server:
  port: 8080

spring:
  application:
    name: matching-service
  config:
    activate:
      on-profile: kubernetes
  messages:
    basename: errors
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      use_sql_comments: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  kakao:
    address:
      secretKey: ${KAKAO_SECRET_KEY}
      url: https://dapi.kakao.com/v2/local/search/address

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    enabled: false