server:
  port: 8080

spring:
  application:
    name: matching-service
  config:
    activate:
      on-profile: kubernetes
  messages:
    basename: errors
  kakao:
    address:
      secretKey: ${KAKAO_SECRET_KEY}
      url: https://dapi.kakao.com/v2/local/search/keyword

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    enabled: false